name: Setup-tf
description: Setup terraform
inputs:
  GHA_ROLE_TO_ASSUME:
    description: AWS Role to Assume from GHA
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6
    - run: yarn install --immutable-cache
      shell: bash
    - run: yarn workspace cdktf-iac get
      shell: bash
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ inputs.GHA_ROLE_TO_ASSUME }}
        aws-region: us-west-2